{{- $clusterInfoExporterEnabled := eq (include "clusterInfoExporter.isEnabled" . | trim) "true" }}
{{- if and $clusterInfoExporterEnabled .Values.clusterInfoExporter.apiClient.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "clusterInfoExporter.apiClientServiceAccountName" . }}
  namespace: {{ include "clusterInfoExporter.apiClientNamespace" . }}
  labels:
    {{- include "clusterInfoExporter.labels" . | nindent 4 }}
{{- end }}
