{{- if and .Values.clusterInfoExporter.enabled .Values.clusterInfoExporter.apiClient.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "clusterInfoExporter.apiClientServiceAccountName" . }}
  namespace: {{ include "clusterInfoExporter.apiClientNamespace" . }}
  labels:
    {{- include "clusterInfoExporter.labels" . | nindent 4 }}
{{- end }}
