{{- $clusterInfoExporterEnabled := eq (include "clusterInfoExporter.isEnabled" . | trim) "true" }}
{{- if and $clusterInfoExporterEnabled .Values.clusterInfoExporter.apiClient.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "clusterInfoExporter.discoveryClusterRoleBindingName" . }}
  labels:
    {{- include "clusterInfoExporter.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "clusterInfoExporter.discoveryClusterRoleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "clusterInfoExporter.apiClientServiceAccountName" . }}
    namespace: {{ include "clusterInfoExporter.apiClientNamespace" . }}
{{- end }}
