{{- $clusterInfoExporterEnabled := eq (include "clusterInfoExporter.isEnabled" . | trim) "true" }}
{{- if and $clusterInfoExporterEnabled .Values.clusterInfoExporter.apiClient.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clusterInfoExporter.apiClientTokenSecretName" . }}
  namespace: {{ include "clusterInfoExporter.apiClientNamespace" . }}
  annotations:
    kubernetes.io/service-account.name: {{ include "clusterInfoExporter.apiClientServiceAccountName" . }}
  labels:
    {{- include "clusterInfoExporter.labels" . | nindent 4 }}
type: kubernetes.io/service-account-token
{{- end }}
