{{- if and .Values.clusterInfoExporter.enabled .Values.clusterInfoExporter.secret.create (not .Values.clusterInfoExporter.secret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clusterInfoExporter.secretName" . }}
  labels:
    {{- include "clusterInfoExporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.clusterInfoExporter.secret.key }}: {{ .Values.clusterInfoExporter.secret.apiToken | quote }}
{{- end }}
