{{- $clusterInfoExporterEnabled := include "clusterInfoExporter.isEnabled" . | fromYaml }}
{{- if and $clusterInfoExporterEnabled .Values.clusterInfoExporter.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "clusterInfoExporter.serviceAccountName" . }}
  labels:
    {{- include "clusterInfoExporter.labels" . | nindent 4 }}
  {{- with .Values.clusterInfoExporter.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
