apiVersion: v2
name: nos
description: The open-source platform for running AI workloads on k8s in an optimized way, both in terms of hardware 
  utilization and workload performance.

type: application
version: 0.0.6
appVersion: "0.0.6"

sources:
  - https://github.com/nebuly-ai/nos

