apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: priority-low
value: 0
description: "Low priority for GPU workloads managed by nos."
preemptionPolicy: Never
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: priority-medium
value: 1000
globalDefault: true
description: "Default priority for GPU workloads managed by nos."
preemptionPolicy: Never
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: priority-high
value: 2000
description: "High priority for GPU workloads managed by nos."
preemptionPolicy: Never
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: priority-extra-high
value: 3000
description: "Extra high priority for GPU workloads managed by nos."
preemptionPolicy: Never
