apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nos-system
namePrefix: nos-

resources:
  - cluster_info_exporter.yaml
  - cluster_info_exporter_config.yaml

images:
  - name: cluster-info-exporter
    newName: ghcr.io/walkai-org/nos-cluster-info-exporter
    newTag: 0.0.1
