apiVersion: v1
kind: Secret
metadata:
  name: api-client-permanent-token
  namespace: walkai
  annotations:
    kubernetes.io/service-account.name: api-client
type: kubernetes.io/service-account-token
